import AdminTemplate from "@/components/managerTemplates";
import menuList from "@/app/sales/menuList";

export const metadata = {
    title: 'Home | Car Showroom',
    description: 'Generated by create next app',
};

type PropsLayout = {
    children: React.ReactNode;
};

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <AdminTemplate title="BURGER QUEEN" id="dashboard" menuList={menuList}>
            {children}
        </AdminTemplate>
    )
}

export default RootLayout;