import SalesTemplate from "@/components/salesTemplates"
import MenuList from "../menuList"

export const metadata = {
   title: 'Dashboard | Ordering System',
   description: 'Generated by create next app',
}

type PropsLayout = {
   children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
   return (
       <SalesTemplate title="BURGER QUEEN" id="dashboard" menuList={MenuList}>
           {children}
       </SalesTemplate>
   )
}

export default RootLayout
